version: "3"
services:
  springboot-app:
    container_name: hogwarts-library-service
    image: milosandric01/hogwarts-library:latest
    restart: always
    build: .
    ports:
      - 8081:8080
    environment:
      MYSQL_HOST: mysqldb
    depends_on:
      - mysqldb
  mysqldb:
    container_name: mysqldb
    image: mysql:8.0
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: hogwarts_library
      MYSQL_ROOT_PASSWORD: root